[2025-01-23T04:19:42.996+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: All_Layer.clean_rating manual__2025-01-23T04:17:24.100143+00:00 [queued]>
[2025-01-23T04:19:43.005+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: All_Layer.clean_rating manual__2025-01-23T04:17:24.100143+00:00 [queued]>
[2025-01-23T04:19:43.006+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2025-01-23T04:19:43.019+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_rating> on 2025-01-23 04:17:24.100143+00:00
[2025-01-23T04:19:43.025+0000] {standard_task_runner.py:57} INFO - Started process 14333 to run task
[2025-01-23T04:19:43.029+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'All_Layer', 'clean_rating', 'manual__2025-01-23T04:17:24.100143+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/All_Offi.py', '--cfg-path', '/tmp/tmpza8zgfn3']
[2025-01-23T04:19:43.032+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask clean_rating
[2025-01-23T04:19:43.080+0000] {task_command.py:416} INFO - Running <TaskInstance: All_Layer.clean_rating manual__2025-01-23T04:17:24.100143+00:00 [running]> on host 73fc507ad5e4
[2025-01-23T04:19:43.160+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='All_Layer' AIRFLOW_CTX_TASK_ID='clean_rating' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T04:17:24.100143+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T04:17:24.100143+00:00'
[2025-01-23T04:19:43.171+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-01-23T04:19:43.173+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_rating.py s3a://lakehouse/bronze/ratings.parquet s3a://lakehouse/silver/ratings
[2025-01-23T04:19:43.326+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-23T04:19:45.281+0000] {spark_submit.py:579} INFO - 25/01/23 04:19:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-23T04:19:45.677+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/processing_rating.py", line 27
[2025-01-23T04:19:45.678+0000] {spark_submit.py:579} INFO - .getOrCreate()
[2025-01-23T04:19:45.679+0000] {spark_submit.py:579} INFO - IndentationError: unexpected indent
[2025-01-23T04:19:45.692+0000] {spark_submit.py:579} INFO - 25/01/23 04:19:45 INFO ShutdownHookManager: Shutdown hook called
[2025-01-23T04:19:45.693+0000] {spark_submit.py:579} INFO - 25/01/23 04:19:45 INFO ShutdownHookManager: Deleting directory /tmp/spark-3b2760e3-d406-40c3-a8b5-7b57115dfd0a
[2025-01-23T04:19:45.745+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_rating.py s3a://lakehouse/bronze/ratings.parquet s3a://lakehouse/silver/ratings. Error code is: 1.
[2025-01-23T04:19:45.751+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=All_Layer, task_id=clean_rating, execution_date=20250123T041724, start_date=20250123T041942, end_date=20250123T041945
[2025-01-23T04:19:45.768+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task clean_rating (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_rating.py s3a://lakehouse/bronze/ratings.parquet s3a://lakehouse/silver/ratings. Error code is: 1.; 14333)
[2025-01-23T04:19:45.814+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T04:19:45.842+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
