[2024-11-14T14:51:46.309+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_flowwww.clean_keyword manual__2024-11-14T14:51:45.642913+00:00 [queued]>
[2024-11-14T14:51:46.327+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_flowwww.clean_keyword manual__2024-11-14T14:51:45.642913+00:00 [queued]>
[2024-11-14T14:51:46.328+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-14T14:51:46.355+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_keyword> on 2024-11-14 14:51:45.642913+00:00
[2024-11-14T14:51:46.361+0000] {standard_task_runner.py:57} INFO - Started process 1683 to run task
[2024-11-14T14:51:46.363+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_flowwww', 'clean_keyword', 'manual__2024-11-14T14:51:45.642913+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/test_flow.py', '--cfg-path', '/tmp/tmp4nm6ez5z']
[2024-11-14T14:51:46.366+0000] {standard_task_runner.py:85} INFO - Job 263: Subtask clean_keyword
[2024-11-14T14:51:46.419+0000] {task_command.py:416} INFO - Running <TaskInstance: test_flowwww.clean_keyword manual__2024-11-14T14:51:45.642913+00:00 [running]> on host 7ea45ba85247
[2024-11-14T14:51:46.507+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_flowwww' AIRFLOW_CTX_TASK_ID='clean_keyword' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T14:51:45.642913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T14:51:45.642913+00:00'
[2024-11-14T14:51:46.518+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-11-14T14:51:46.520+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/test_Key.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/sliver/keywords
[2024-11-14T14:51:46.693+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-11-14T14:51:48.793+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-11-14T14:51:48.950+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-11-14T14:51:48.951+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-11-14T14:51:48.955+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-11-14T14:51:48.957+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-44093699-9338-4bb7-9d96-c9b1c6388cde;1.0
[2024-11-14T14:51:48.958+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-11-14T14:51:49.093+0000] {spark_submit.py:579} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2024-11-14T14:51:49.119+0000] {spark_submit.py:579} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2024-11-14T14:51:49.145+0000] {spark_submit.py:579} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-11-14T14:51:52.441+0000] {spark_submit.py:579} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar ...
[2024-11-14T14:57:34.281+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-14T14:57:34.284+0000] {process_utils.py:131} INFO - Sending 15 to group 1683. PIDs of all processes in the group: [1684, 1683]
[2024-11-14T14:57:34.285+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1683
[2024-11-14T14:57:34.285+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-14T14:57:34.286+0000] {spark_submit.py:705} INFO - Sending kill signal to spark-submit
[2024-11-14T14:57:34.338+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1683, status='terminated', exitcode=0, started='14:51:45') (1683) terminated with exit code 0
[2024-11-14T14:57:34.339+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1684, status='terminated', started='14:51:45') (1684) terminated with exit code None
