[2025-01-23T04:20:28.365+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: All_Layer.clean_credit manual__2025-01-23T04:17:24.100143+00:00 [queued]>
[2025-01-23T04:20:28.376+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: All_Layer.clean_credit manual__2025-01-23T04:17:24.100143+00:00 [queued]>
[2025-01-23T04:20:28.377+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2025-01-23T04:20:28.389+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_credit> on 2025-01-23 04:17:24.100143+00:00
[2025-01-23T04:20:28.396+0000] {standard_task_runner.py:57} INFO - Started process 14449 to run task
[2025-01-23T04:20:28.400+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'All_Layer', 'clean_credit', 'manual__2025-01-23T04:17:24.100143+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/All_Offi.py', '--cfg-path', '/tmp/tmp2qoq9fcd']
[2025-01-23T04:20:28.403+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask clean_credit
[2025-01-23T04:20:28.453+0000] {task_command.py:416} INFO - Running <TaskInstance: All_Layer.clean_credit manual__2025-01-23T04:17:24.100143+00:00 [running]> on host 73fc507ad5e4
[2025-01-23T04:20:28.534+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='All_Layer' AIRFLOW_CTX_TASK_ID='clean_credit' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T04:17:24.100143+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T04:17:24.100143+00:00'
[2025-01-23T04:20:28.544+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-01-23T04:20:28.546+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_credit.py s3a://lakehouse/bronze/credits.parquet s3a://lakehouse/silver/credit
[2025-01-23T04:20:28.706+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-23T04:20:30.437+0000] {spark_submit.py:579} INFO - 25/01/23 04:20:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-23T04:20:30.838+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/processing_credit.py", line 36
[2025-01-23T04:20:30.839+0000] {spark_submit.py:579} INFO - .getOrCreate()
[2025-01-23T04:20:30.839+0000] {spark_submit.py:579} INFO - IndentationError: unexpected indent
[2025-01-23T04:20:30.853+0000] {spark_submit.py:579} INFO - 25/01/23 04:20:30 INFO ShutdownHookManager: Shutdown hook called
[2025-01-23T04:20:30.854+0000] {spark_submit.py:579} INFO - 25/01/23 04:20:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-0b1e10d6-866c-426d-a81c-894ddfe24414
[2025-01-23T04:20:30.895+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_credit.py s3a://lakehouse/bronze/credits.parquet s3a://lakehouse/silver/credit. Error code is: 1.
[2025-01-23T04:20:30.900+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=All_Layer, task_id=clean_credit, execution_date=20250123T041724, start_date=20250123T042028, end_date=20250123T042030
[2025-01-23T04:20:30.923+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 103 for task clean_credit (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_credit.py s3a://lakehouse/bronze/credits.parquet s3a://lakehouse/silver/credit. Error code is: 1.; 14449)
[2025-01-23T04:20:30.941+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T04:20:30.969+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
