[2024-11-14T15:36:02.635+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_flowwww.clean_keyword manual__2024-11-14T15:36:01.336327+00:00 [queued]>
[2024-11-14T15:36:02.649+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_flowwww.clean_keyword manual__2024-11-14T15:36:01.336327+00:00 [queued]>
[2024-11-14T15:36:02.650+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-14T15:36:02.666+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_keyword> on 2024-11-14 15:36:01.336327+00:00
[2024-11-14T15:36:02.671+0000] {standard_task_runner.py:57} INFO - Started process 436 to run task
[2024-11-14T15:36:02.673+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_flowwww', 'clean_keyword', 'manual__2024-11-14T15:36:01.336327+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/test_flow.py', '--cfg-path', '/tmp/tmpdfdof10b']
[2024-11-14T15:36:02.675+0000] {standard_task_runner.py:85} INFO - Job 265: Subtask clean_keyword
[2024-11-14T15:36:02.723+0000] {task_command.py:416} INFO - Running <TaskInstance: test_flowwww.clean_keyword manual__2024-11-14T15:36:01.336327+00:00 [running]> on host 7ea45ba85247
[2024-11-14T15:36:02.812+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_flowwww' AIRFLOW_CTX_TASK_ID='clean_keyword' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T15:36:01.336327+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T15:36:01.336327+00:00'
[2024-11-14T15:36:02.822+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-11-14T15:36:02.825+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/test_Key.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/sliver/keywords
[2024-11-14T15:36:02.997+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-11-14T15:36:06.010+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-11-14T15:36:06.145+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-11-14T15:36:06.146+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-11-14T15:36:06.151+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-11-14T15:36:06.152+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-7060147e-c7cc-4908-a70a-9a6f28b797ee;1.0
[2024-11-14T15:36:06.153+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-11-14T15:36:06.343+0000] {spark_submit.py:579} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2024-11-14T15:36:06.382+0000] {spark_submit.py:579} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2024-11-14T15:36:06.419+0000] {spark_submit.py:579} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-11-14T15:36:09.956+0000] {spark_submit.py:579} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar ...
[2024-11-14T16:08:30.733+0000] {spark_submit.py:579} INFO - downloading https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.0.7.Final/wildfly-openssl-1.0.7.Final.jar ...
[2024-11-14T16:08:31.813+0000] {spark_submit.py:579} INFO - [SUCCESSFUL ] org.wildfly.openssl#wildfly-openssl;1.0.7.Final!wildfly-openssl.jar (2056ms)
[2024-11-14T16:08:31.814+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 299ms :: artifacts dl 1945362ms
[2024-11-14T16:08:31.814+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-11-14T16:08:31.815+0000] {spark_submit.py:579} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2024-11-14T16:08:31.815+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
[2024-11-14T16:08:31.815+0000] {spark_submit.py:579} INFO - org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-11-14T16:08:31.816+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-11-14T16:08:31.816+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-11-14T16:08:31.816+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-11-14T16:08:31.816+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-11-14T16:08:31.817+0000] {spark_submit.py:579} INFO - |      default     |   3   |   0   |   0   |   0   ||   3   |   1   |
[2024-11-14T16:08:31.817+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-11-14T16:08:31.819+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.820+0000] {spark_submit.py:579} INFO - :: problems summary ::
[2024-11-14T16:08:31.820+0000] {spark_submit.py:579} INFO - :::: WARNINGS
[2024-11-14T16:08:31.820+0000] {spark_submit.py:579} INFO - [FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar: Downloaded file size (194251495) doesn't match expected Content Length (280645251) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar. Please retry. (1943279ms)
[2024-11-14T16:08:31.821+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.821+0000] {spark_submit.py:579} INFO - [FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar: Downloaded file size (194251495) doesn't match expected Content Length (280645251) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar. Please retry. (1943279ms)
[2024-11-14T16:08:31.821+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.822+0000] {spark_submit.py:579} INFO - ==== central: tried
[2024-11-14T16:08:31.822+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.822+0000] {spark_submit.py:579} INFO - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
[2024-11-14T16:08:31.822+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.823+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2024-11-14T16:08:31.823+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.823+0000] {spark_submit.py:579} INFO - ::              FAILED DOWNLOADS            ::
[2024-11-14T16:08:31.823+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.824+0000] {spark_submit.py:579} INFO - :: ^ see resolution messages for details  ^ ::
[2024-11-14T16:08:31.824+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.824+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2024-11-14T16:08:31.825+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.825+0000] {spark_submit.py:579} INFO - :: com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar
[2024-11-14T16:08:31.825+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.825+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2024-11-14T16:08:31.826+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.826+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.826+0000] {spark_submit.py:579} INFO - 
[2024-11-14T16:08:31.826+0000] {spark_submit.py:579} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-11-14T16:08:31.827+0000] {spark_submit.py:579} INFO - Exception in thread "main" java.lang.RuntimeException: [download failed: com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar]
[2024-11-14T16:08:31.827+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2024-11-14T16:08:31.827+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2024-11-14T16:08:31.827+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2024-11-14T16:08:31.827+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2024-11-14T16:08:31.828+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2024-11-14T16:08:31.828+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2024-11-14T16:08:31.828+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2024-11-14T16:08:31.828+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-11-14T16:08:31.829+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-11-14T16:08:31.829+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-11-14T16:08:31.862+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/test_Key.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/sliver/keywords. Error code is: 1.
[2024-11-14T16:08:31.867+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test_flowwww, task_id=clean_keyword, execution_date=20241114T153601, start_date=20241114T153602, end_date=20241114T160831
[2024-11-14T16:08:31.886+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 265 for task clean_keyword (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/test_Key.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/sliver/keywords. Error code is: 1.; 436)
[2024-11-14T16:08:31.921+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-14T16:08:31.946+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
