[2024-10-03T14:29:40.698+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T14:29:40.708+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T14:29:40.708+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-03T14:29:40.722+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): bronze_keywords> on 2024-10-02 00:00:00+00:00
[2024-10-03T14:29:40.730+0000] {standard_task_runner.py:57} INFO - Started process 238 to run task
[2024-10-03T14:29:40.733+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bronze_layer_processing', 'bronze_keywords', 'scheduled__2024-10-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/bronze_layer.py', '--cfg-path', '/tmp/tmphi25va1j']
[2024-10-03T14:29:40.736+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask bronze_keywords
[2024-10-03T14:29:40.836+0000] {task_command.py:415} INFO - Running <TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-02T00:00:00+00:00 [running]> on host 9da41aea9375
[2024-10-03T14:29:40.934+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bronze_layer_processing' AIRFLOW_CTX_TASK_ID='bronze_keywords' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:00:00+00:00'
[2024-10-03T14:29:40.936+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 38, in bronze_keywords
    df = get_data_from_raw('keywords')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 24, in get_data_from_raw
    client = connect_minio()
             ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 15, in connect_minio
    endpoint_url='http://' + os.getenv("MINIO_ENDPOINT")
                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
[2024-10-03T14:29:40.949+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_layer_processing, task_id=bronze_keywords, execution_date=20241002T000000, start_date=20241003T142940, end_date=20241003T142940
[2024-10-03T14:29:40.960+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task bronze_keywords (can only concatenate str (not "NoneType") to str; 238)
[2024-10-03T14:29:40.987+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-03T14:29:41.012+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
