[2025-01-23T03:54:27.351+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: All_Layer.clean_review manual__2025-01-23T03:54:02.576089+00:00 [queued]>
[2025-01-23T03:54:27.368+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: All_Layer.clean_review manual__2025-01-23T03:54:02.576089+00:00 [queued]>
[2025-01-23T03:54:27.368+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-23T03:54:27.389+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_review> on 2025-01-23 03:54:02.576089+00:00
[2025-01-23T03:54:27.401+0000] {standard_task_runner.py:57} INFO - Started process 9980 to run task
[2025-01-23T03:54:27.402+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'All_Layer', 'clean_review', 'manual__2025-01-23T03:54:02.576089+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/All_Offi.py', '--cfg-path', '/tmp/tmp9c5rk7gv']
[2025-01-23T03:54:27.405+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask clean_review
[2025-01-23T03:54:27.468+0000] {task_command.py:416} INFO - Running <TaskInstance: All_Layer.clean_review manual__2025-01-23T03:54:02.576089+00:00 [running]> on host 73fc507ad5e4
[2025-01-23T03:54:27.566+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='All_Layer' AIRFLOW_CTX_TASK_ID='clean_review' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T03:54:02.576089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T03:54:02.576089+00:00'
[2025-01-23T03:54:27.578+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-01-23T03:54:27.582+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_review.py s3a://lakehouse/bronze/review.parquet s3a://lakehouse/silver/review
[2025-01-23T03:54:27.933+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-23T03:54:32.378+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-01-23T03:54:32.803+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-01-23T03:54:32.818+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-01-23T03:54:32.822+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-01-23T03:54:32.835+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-0f627be1-4d53-44fd-a3f7-1437624726f1;1.0
[2025-01-23T03:54:32.847+0000] {spark_submit.py:579} INFO - confs: [default]
[2025-01-23T03:54:33.152+0000] {spark_submit.py:579} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2025-01-23T03:54:33.258+0000] {spark_submit.py:579} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2025-01-23T03:54:33.382+0000] {spark_submit.py:579} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-01-23T03:54:33.489+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 615ms :: artifacts dl 46ms
[2025-01-23T03:54:33.493+0000] {spark_submit.py:579} INFO - :: modules in use:
[2025-01-23T03:54:33.493+0000] {spark_submit.py:579} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2025-01-23T03:54:33.494+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
[2025-01-23T03:54:33.494+0000] {spark_submit.py:579} INFO - org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-01-23T03:54:33.495+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2025-01-23T03:54:33.495+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2025-01-23T03:54:33.495+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-01-23T03:54:33.496+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2025-01-23T03:54:33.496+0000] {spark_submit.py:579} INFO - |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2025-01-23T03:54:33.497+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2025-01-23T03:54:33.516+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-0f627be1-4d53-44fd-a3f7-1437624726f1
[2025-01-23T03:54:33.517+0000] {spark_submit.py:579} INFO - confs: [default]
[2025-01-23T03:54:33.567+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 3 already retrieved (0kB/42ms)
[2025-01-23T03:54:34.392+0000] {spark_submit.py:579} INFO - 25/01/23 03:54:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-23T03:54:35.473+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/processing_review.py", line 26
[2025-01-23T03:54:35.474+0000] {spark_submit.py:579} INFO - .getOrCreate()
[2025-01-23T03:54:35.475+0000] {spark_submit.py:579} INFO - IndentationError: unexpected indent
[2025-01-23T03:54:35.500+0000] {spark_submit.py:579} INFO - 25/01/23 03:54:35 INFO ShutdownHookManager: Shutdown hook called
[2025-01-23T03:54:35.501+0000] {spark_submit.py:579} INFO - 25/01/23 03:54:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-b9bee255-581f-48ff-b0e0-6daec3c407bb
[2025-01-23T03:54:35.582+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_review.py s3a://lakehouse/bronze/review.parquet s3a://lakehouse/silver/review. Error code is: 1.
[2025-01-23T03:54:35.588+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=All_Layer, task_id=clean_review, execution_date=20250123T035402, start_date=20250123T035427, end_date=20250123T035435
[2025-01-23T03:54:35.602+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task clean_review (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_review.py s3a://lakehouse/bronze/review.parquet s3a://lakehouse/silver/review. Error code is: 1.; 9980)
[2025-01-23T03:54:35.635+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T03:54:35.699+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
