[2024-10-04T02:26:35.171+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_dag.silver_cleaned_keywords scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T02:26:35.181+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_dag.silver_cleaned_keywords scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T02:26:35.182+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-04T02:26:35.195+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): silver_cleaned_keywords> on 2024-10-03 00:00:00+00:00
[2024-10-04T02:26:35.201+0000] {standard_task_runner.py:57} INFO - Started process 2631 to run task
[2024-10-04T02:26:35.204+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_dag', 'silver_cleaned_keywords', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/sliver_layer.py', '--cfg-path', '/tmp/tmpigzqorjj']
[2024-10-04T02:26:35.208+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask silver_cleaned_keywords
[2024-10-04T02:26:35.276+0000] {task_command.py:415} INFO - Running <TaskInstance: spark_processing_dag.silver_cleaned_keywords scheduled__2024-10-03T00:00:00+00:00 [running]> on host 928e276d789d
[2024-10-04T02:26:35.354+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_dag' AIRFLOW_CTX_TASK_ID='silver_cleaned_keywords' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T02:26:35.365+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-04T02:26:35.368+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar,/opt/bitnami/spark/jars/s3-2.18.41.jar,/opt/bitnami/spark/jars/aws-java-sdk-1.12.367.jar,/opt/bitnami/spark/jars/delta-core_2.12-2.3.0.jar,/opt/bitnami/spark/jars/delta-storage-2.3.0.jar,/opt/bitnami/spark/jars/mysql-connector-java-8.0.19.jar --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/bitnami/***/scripts/test_Key.py
[2024-10-04T02:26:35.470+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-10-04T02:26:37.712+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-10-04T02:26:37.869+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-10-04T02:26:37.872+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-10-04T02:26:37.879+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-10-04T02:26:37.881+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-51328350-4bca-4ce9-97a5-4f59ae07185e;1.0
[2024-10-04T02:26:37.882+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-10-04T02:26:41.287+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 3405ms :: artifacts dl 0ms
[2024-10-04T02:26:41.289+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-10-04T02:26:41.291+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-10-04T02:26:41.292+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-10-04T02:26:41.294+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-10-04T02:26:41.297+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-10-04T02:26:41.297+0000] {spark_submit.py:579} INFO - |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2024-10-04T02:26:41.298+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-10-04T02:26:41.298+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.298+0000] {spark_submit.py:579} INFO - :: problems summary ::
[2024-10-04T02:26:41.299+0000] {spark_submit.py:579} INFO - :::: WARNINGS
[2024-10-04T02:26:41.299+0000] {spark_submit.py:579} INFO - problem while downloading module descriptor: https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom: Downloaded file size (0) doesn't match expected Content Length (25377) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom. Please retry. (259ms)
[2024-10-04T02:26:41.299+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.300+0000] {spark_submit.py:579} INFO - module not found: org.apache.hadoop#hadoop-aws;3.3.4
[2024-10-04T02:26:41.301+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.302+0000] {spark_submit.py:579} INFO - ==== local-m2-cache: tried
[2024-10-04T02:26:41.302+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.303+0000] {spark_submit.py:579} INFO - file:/home/***/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom
[2024-10-04T02:26:41.303+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.303+0000] {spark_submit.py:579} INFO - -- artifact org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar:
[2024-10-04T02:26:41.304+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.304+0000] {spark_submit.py:579} INFO - file:/home/***/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
[2024-10-04T02:26:41.304+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.305+0000] {spark_submit.py:579} INFO - ==== local-ivy-cache: tried
[2024-10-04T02:26:41.305+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.305+0000] {spark_submit.py:579} INFO - /home/***/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.4/ivys/ivy.xml
[2024-10-04T02:26:41.306+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.306+0000] {spark_submit.py:579} INFO - -- artifact org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar:
[2024-10-04T02:26:41.306+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.306+0000] {spark_submit.py:579} INFO - /home/***/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.4/jars/hadoop-aws.jar
[2024-10-04T02:26:41.307+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.310+0000] {spark_submit.py:579} INFO - ==== central: tried
[2024-10-04T02:26:41.311+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.312+0000] {spark_submit.py:579} INFO - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom
[2024-10-04T02:26:41.314+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.315+0000] {spark_submit.py:579} INFO - ==== spark-packages: tried
[2024-10-04T02:26:41.316+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.317+0000] {spark_submit.py:579} INFO - https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom
[2024-10-04T02:26:41.317+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.317+0000] {spark_submit.py:579} INFO - -- artifact org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar:
[2024-10-04T02:26:41.318+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.318+0000] {spark_submit.py:579} INFO - https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
[2024-10-04T02:26:41.318+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.319+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2024-10-04T02:26:41.319+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.319+0000] {spark_submit.py:579} INFO - ::          UNRESOLVED DEPENDENCIES         ::
[2024-10-04T02:26:41.319+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.320+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2024-10-04T02:26:41.320+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.320+0000] {spark_submit.py:579} INFO - :: org.apache.hadoop#hadoop-aws;3.3.4: not found
[2024-10-04T02:26:41.321+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.322+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2024-10-04T02:26:41.323+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.323+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.323+0000] {spark_submit.py:579} INFO - 
[2024-10-04T02:26:41.324+0000] {spark_submit.py:579} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-10-04T02:26:41.324+0000] {spark_submit.py:579} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.hadoop#hadoop-aws;3.3.4: not found]
[2024-10-04T02:26:41.324+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1608)
[2024-10-04T02:26:41.325+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2024-10-04T02:26:41.325+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2024-10-04T02:26:41.325+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2024-10-04T02:26:41.326+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-10-04T02:26:41.326+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-10-04T02:26:41.326+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-10-04T02:26:41.326+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-10-04T02:26:41.327+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-10-04T02:26:41.327+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-10-04T02:26:41.338+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar,/opt/bitnami/spark/jars/s3-2.18.41.jar,/opt/bitnami/spark/jars/aws-java-sdk-1.12.367.jar,/opt/bitnami/spark/jars/delta-core_2.12-2.3.0.jar,/opt/bitnami/spark/jars/delta-storage-2.3.0.jar,/opt/bitnami/spark/jars/mysql-connector-java-8.0.19.jar --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/bitnami/***/scripts/test_Key.py. Error code is: 1.
[2024-10-04T02:26:41.345+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_processing_dag, task_id=silver_cleaned_keywords, execution_date=20241003T000000, start_date=20241004T022635, end_date=20241004T022641
[2024-10-04T02:26:41.358+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task silver_cleaned_keywords (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar,/opt/bitnami/spark/jars/s3-2.18.41.jar,/opt/bitnami/spark/jars/aws-java-sdk-1.12.367.jar,/opt/bitnami/spark/jars/delta-core_2.12-2.3.0.jar,/opt/bitnami/spark/jars/delta-storage-2.3.0.jar,/opt/bitnami/spark/jars/mysql-connector-java-8.0.19.jar --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/bitnami/***/scripts/test_Key.py. Error code is: 1.; 2631)
[2024-10-04T02:26:41.373+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-04T02:26:41.388+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
